SELECT * FROM OUR_FIRST_DATABASE.PUBLIC.EMPLOYEES;

// Creating permanent clone table
CREATE OR REPLACE TABLE OUR_FIRST_DATABASE.PUBLIC.EMPLOYEES_CLONE
CLONE OUR_FIRST_DATABASE.PUBLIC.EMPLOYEES;

SELECT * FROM OUR_FIRST_DATABASE.PUBLIC.EMPLOYEES_CLONE;

// Update clone table
UPDATE OUR_FIRST_DATABASE.PUBLIC.EMPLOYEES_CLONE
SET EMAIL = null;

// Creating temporary clone table
CREATE OR REPLACE TEMPORARY TABLE OUR_FIRST_DATABASE.PUBLIC.EMPLOYEES_CLONE_TEMP
CLONE OUR_FIRST_DATABASE.PUBLIC.EMPLOYEES;

SHOW TABLES;